name: Scheduled CI with Gradle

on:
  schedule:
    - cron: '30 12 * * 3'  # Run every Wednesday at 12:30
    - cron: '0 22 * * 5'   # Run every Friday at 22:00

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build
